// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbm6RXYotJSDwc88-nnlzvKBOjqodmgQI',
    appId: '1:700124896834:web:1319cb5cc74a70a26197db',
    messagingSenderId: '700124896834',
    projectId: 'madlab-ronn-db',
    authDomain: 'madlab-ronn-db.firebaseapp.com',
    storageBucket: 'madlab-ronn-db.firebasestorage.app',
    measurementId: 'G-2P2T26G4ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU8tPJ5sRe_yMeX_2C-A_ufZpYvqvgUu8',
    appId: '1:700124896834:android:e9d7c4eb928b6d696197db',
    messagingSenderId: '700124896834',
    projectId: 'madlab-ronn-db',
    storageBucket: 'madlab-ronn-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmvNTaZtLfJhXLK5M7yua5VMdgk6npncQ',
    appId: '1:700124896834:ios:3191d890af7a84bf6197db',
    messagingSenderId: '700124896834',
    projectId: 'madlab-ronn-db',
    storageBucket: 'madlab-ronn-db.firebasestorage.app',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmvNTaZtLfJhXLK5M7yua5VMdgk6npncQ',
    appId: '1:700124896834:ios:3191d890af7a84bf6197db',
    messagingSenderId: '700124896834',
    projectId: 'madlab-ronn-db',
    storageBucket: 'madlab-ronn-db.firebasestorage.app',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbm6RXYotJSDwc88-nnlzvKBOjqodmgQI',
    appId: '1:700124896834:web:50f5c55c3d0964016197db',
    messagingSenderId: '700124896834',
    projectId: 'madlab-ronn-db',
    authDomain: 'madlab-ronn-db.firebaseapp.com',
    storageBucket: 'madlab-ronn-db.firebasestorage.app',
    measurementId: 'G-6E83W5DCEX',
  );
}
